### PR TITLE
Add teams feature to the community theme

### PR DESCRIPTION
**Pull request by bitterdev**
You need to update the core first before you update or install this package.

### CODE REVIEW

**Comment by bitterdev** [comment]
Added new login + register pages to this PR

**Comment by bitterdev** [comment]
Added dark mode to this PR.

You need to update the Core first (see PR https://github.com/concrete5/concrete5/pull/9373)

**Comment by aembler** [comment]
I believe we're still waiting on #9373 from the concrete5 project to be updated before I can merge this in.

**Comment by bitterdev** [comment]
Added showcase feature

**Comment by bitterdev** [comment]
Moved showcase code to https://github.com/concrete5/community.concretecms.com

**Pull request merged**
